@startuml

title __APP's Class Diagram__\n

  namespace com.example.workinprogress {
    class com.example.workinprogress.About {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.BuildConfig {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.DataDisplay {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.DisplayImage {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.Gallery {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.GalleryRecyclerViewAdapter {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.Location {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.MainActivity {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.Position {
    }
  }
  

  namespace com.example.workinprogress {
    interface com.example.workinprogress.ResultValuesAppendable {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.ScaledValues {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.SensorResult {
    }
  }
  

  namespace com.example.workinprogress {
    class com.example.workinprogress.ShortPortrait {
    }
  }
  

  namespace com.example.workinprogress {
    namespace paintings {
      class com.example.workinprogress.paintings.AlbersImage {
      }
    }
  }
  

  namespace com.example.workinprogress {
    namespace paintings {
      class com.example.workinprogress.paintings.Painting {
      }
    }
  }
  

  namespace com.example.workinprogress {
    namespace paintings {
      class com.example.workinprogress.paintings.TextImage {
      }
    }
  }
  

  com.example.workinprogress.About -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.workinprogress.DataDisplay -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.workinprogress.DisplayImage -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.workinprogress.DisplayImage o-- com.example.workinprogress.paintings.Painting : createdImage
  com.example.workinprogress.Gallery -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.workinprogress.Gallery o-- com.example.workinprogress.GalleryRecyclerViewAdapter : galleryRecyclerViewAdapter
  com.example.workinprogress.GalleryRecyclerViewAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.workinprogress.Location .up.|> com.example.workinprogress.ResultValuesAppendable
  com.example.workinprogress.Location .up.|> java.io.Serializable
  com.example.workinprogress.MainActivity .up.|> com.google.android.gms.common.api.GoogleApiClient.ConnectionCallbacks
  com.example.workinprogress.MainActivity .up.|> com.google.android.gms.common.api.GoogleApiClient.OnConnectionFailedListener
  com.example.workinprogress.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.workinprogress.Position .up.|> com.example.workinprogress.ResultValuesAppendable
  com.example.workinprogress.Position .up.|> java.io.Serializable
  com.example.workinprogress.SensorResult .up.|> java.io.Serializable
  com.example.workinprogress.ShortPortrait .up.|> android.hardware.SensorEventListener
  com.example.workinprogress.ShortPortrait .up.|> android.location.LocationListener
  com.example.workinprogress.ShortPortrait -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.workinprogress.paintings.AlbersImage -up-|> com.example.workinprogress.paintings.Painting
  com.example.workinprogress.paintings.Painting -up-|> android.graphics.drawable.Drawable
  com.example.workinprogress.paintings.TextImage -up-|> com.example.workinprogress.paintings.Painting


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
